##---------------------------------------------------------------------------##
# Spring Batch Master Class
##---------------------------------------------------------------------------##
# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
# TO Revisit:
# https://github.com/AnySoftKeyboard/AnySoftKeyboard/blob/master/circle.yml
##---------------------------------------------------------------------------##
version: 2.0

jobs:

##---------------------------------------------------------------------------##
  batch_section_core:
    docker:
      - image: circleci/openjdk:8-jdk-browsers

    environment:
      BASE_DIR: "./StudentWork/code"
      _JAVA_OPTIONS: "-Xms512m -Xmx1024m"

    #working_directory: ~/tmp/workspace
    working_directory: ~/circleci-mfk-workflows

    steps:
      - checkout
      - run:
          name: Initialize JUnit Dir
          command: |
            set -xu
            echo $CIRCLE_WORKING_DIRECTORY
            mkdir -p ~/junit/

  bundle_dependencies:
    docker:
      - image: circleci/ruby:2.4-node-jessie
      - image: circleci/postgres:9.4.12-alpine
    working_directory: ~/circleci-demo-workflows
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/circleci-demo-workflows/vendor/bundle

  ##---------------------------------------------------------------------------##
workflows:
  version: 2.0
    build-and-deploy:
      jobs:
        - batch_section_core

##---------------------------------------------------------------------------##
## The End... ##
##---------------------------------------------------------------------------##
