##---------------------------------------------------------------------------##
# Service Configuration
##---------------------------------------------------------------------------##
debug: ${DEBUG_MODE:false}

server:
  port: ${SERVER_PORT:8080}

##---------------------------------------------------------------------------##
spring:
  application:
    name: batch-introduction


serviceId: ${SERVICE_ID:batch-introduction}


##---------------------------------------------------------------------------##


##---------------------------------------------------------------------------##
# MODULE SPECIFIC PROPERTIES
inputName: products.csv
stepName: step1
jobName: job1



##---------------------------------------------------------------------------##
logging:
  level:
    root: 'INFO'
    org.springframework: 'INFO'

##---------------------------------------------------------------------------##
## NOTE: Enable Management endpoints

management:
  #  see ActuatorSecurity.java
  #  security:
  #    enabled: false

  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"

  # Allow all details for Hystrix dashboard
  endpoint:
    health:
      show-details: always

##---------------------------------------------------------------------------##
#spring.profiles.active: SBA

##---------------------------------------------------------------------------##
## NOTE: Spring Boot Admin Application Profile Properties
---

spring:
  profiles: SBA


# SBA Client details:
spring.boot.admin.username: ${ADMIN_SERVER_USERNAME:admin}
spring.boot.admin.password: ${ADMIN_SERVER_PASSWORD:admin}

spring.boot.admin.client.url: ${ADMIN_SERVER_URL:http://localhost:1111}


##---------------------------------------------------------------------------##
