##---------------------------------------------------------------------------##
# Service Configuration
##---------------------------------------------------------------------------##
debug: ${DEBUG_MODE:false}

server:
  port: ${SERVER_PORT:8080}

##---------------------------------------------------------------------------##
spring:
  application:
    name: batch-introduction






##---------------------------------------------------------------------------##
# BATCH CONFIGURATION

  ## H2 Servlet setting (disabled for now)
  ## connection URL: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /admin/h2



serviceId: ${SERVICE_ID:batch-introduction}

#spring.cloud.refresh.enabled: false

##---------------------------------------------------------------------------##
# MODULE SPECIFIC PROPERTIES


##---------------------------------------------------------------------------##
# Logging and Console
logging:
  level:
    root: 'INFO'
    org.springframework: 'INFO'
    org.h2.jdbc.JdbcSQLException: 'ERROR'

#spring.main.banner-mode: off
spring.output.ansi.enabled: ALWAYS

##---------------------------------------------------------------------------##
## NOTE: Enable Management endpoints

management:
  #  see ActuatorSecurity.java
  #  security:
  #    enabled: false

  endpoints:
    jmx:
      exposure:
        include: "*"
    web:
      exposure:
        include: "*"

  # Allow all details for Hystrix dashboard
  endpoint:
    health:
      show-details: always

##---------------------------------------------------------------------------##
#spring.profiles.active: SBA

##---------------------------------------------------------------------------##
## NOTE: Spring Boot Admin Application Profile Properties
---

spring:
  profiles: SBA


# SBA Client details:
spring.boot.admin.username: ${ADMIN_SERVER_USERNAME:admin}
spring.boot.admin.password: ${ADMIN_SERVER_PASSWORD:admin}

spring.boot.admin.client.url: ${ADMIN_SERVER_URL:http://localhost:1111}


##---------------------------------------------------------------------------##
